version: '3'

services:
  db:
    image: postgis/postgis:14-3.4
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      
  redis:
    image: redis:8.6
    container_name: redis_pta
    ports:
      - 6379:6379
volumes:
  db-store: